# Generated by Django 4.0.2 on 2022-11-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDatabase',
            new_name='EmployeeDatabase',
        ),
        migrations.AlterModelOptions(
            name='employeedatabase',
            options={'verbose_name_plural': 'EmployeeDB'},
        ),
    ]
